name: ci
on: [deployment_status]
jobs:
  e2e:
    # only runs this job once Vercel has deployed our preview environment
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}